import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("suggestions", "routes/suggestions.tsx"),
    route("messages", "routes/messages.tsx"),
    route("alerts", "routes/alerts.tsx"),
    route("settings", "routes/settings.tsx"),
    route("add", "routes/add.tsx"),
    route("selected", "routes/selected.tsx"),
    route("pescadero", "routes/facilities/pescadero.tsx"),
    route("portland", "routes/facilities/portland.tsx"),
    route("savannah", "routes/facilities/savannah.tsx"),
    route("santa-fe", "routes/facilities/santa-fe.tsx"),
    route("bozeman", "routes/facilities/bozeman.tsx"),
    route("burlington", "routes/facilities/burlington.tsx"),
    route("sedona", "routes/facilities/sedona.tsx"),
    route("charleston", "routes/facilities/charleston.tsx"),
    route("asheville", "routes/facilities/asheville.tsx"),
    route("moab", "routes/facilities/moab.tsx"),
    route("key-west", "routes/facilities/key-west.tsx"),
    route("juneau", "routes/facilities/juneau.tsx"),
    route("taos", "routes/facilities/taos.tsx"),
    route("bar-harbor", "routes/facilities/bar-harbor.tsx"),
    route("telluride", "routes/facilities/telluride.tsx"),
    route("carmel", "routes/facilities/carmel.tsx"),
    route("jackson", "routes/facilities/jackson.tsx"),
    route("kauai", "routes/facilities/kauai.tsx"),
    route("nantucket", "routes/facilities/nantucket.tsx"),
    route("lake-tahoe", "routes/facilities/lake-tahoe.tsx"),
] satisfies RouteConfig;
